/**
 * Age Gate Authentication Scaffold
 * Addresses: coppa-auth-001 (CRITICAL), asaa-av-004 (CRITICAL)
 * Generates an age verification gate with three-tier categorization:
 *   - Under 13: COPPA (blocked or requires VPC)
 *   - 13-17: ASAA teen tier (requires parental consent)
 *   - 18+: Adult (full access)
 */

import type { Framework } from '../../framework-detect';
import type { ScaffoldTemplate, ScaffoldFile } from '../index';

function generateReact(typescript: boolean): ScaffoldFile[] {
  const ext = typescript ? 'tsx' : 'jsx';
  const typeAnnotation = typescript ? ': string' : '';
  const stateType = typescript ? '<boolean>' : '';
  const eventType = typescript ? ': React.FormEvent<HTMLFormElement>' : '';
  const changeType = typescript ? ': React.ChangeEvent<HTMLInputElement>' : '';
  const propsType = typescript
    ? `\ntype AgeCategory = 'child' | 'teen' | 'adult';\n\ninterface AgeGateProps {\n  children: React.ReactNode;\n  minimumAge?: number;\n  onVerified?: (category: AgeCategory) => void;\n  onBlocked?: () => void;\n  onTeenDetected?: () => void;\n}\n`
    : '';
  const propsArg = typescript ? '{ children, minimumAge = 13, onVerified, onBlocked, onTeenDetected }: AgeGateProps' : '{ children, minimumAge = 13, onVerified, onBlocked, onTeenDetected }';

  const component = `/**
 * AgeGate — COPPA-compliant age verification component
 *
 * Blocks access for users under the minimum age (default: 13).
 * Uses date-of-birth verification (not simple yes/no buttons).
 * Stores verification in sessionStorage (not persistent — COPPA best practice).
 *
 * Usage:
 *   <AgeGate>
 *     <YourProtectedContent />
 *   </AgeGate>
 *
 * Generated by Halo (runhalo.dev) — COPPA compliance scaffold
 */

import React, { useState, useCallback } from 'react';
${propsType}
const AGE_GATE_KEY = 'halo_age_verified';

export function AgeGate(${propsArg}) {
  const [verified, setVerified] = useState${stateType}(() => {
    // Check sessionStorage (not localStorage — don't persist across sessions)
    if (typeof window !== 'undefined') {
      const stored = sessionStorage.getItem(AGE_GATE_KEY);
      return stored === 'adult' || stored === 'true'; // 'true' for backwards compat
    }
    return false;
  });
  const [dob, setDob] = useState${typescript ? '<string>' : ''}('');
  const [error, setError] = useState${typescript ? '<string>' : ''}('');
  const [blocked, setBlocked] = useState${stateType}(false);

  const handleSubmit = useCallback((e${eventType}) => {
    e.preventDefault();
    setError('');

    if (!dob) {
      setError('Please enter your date of birth.');
      return;
    }

    const birthDate = new Date(dob);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }

    // ASAA three-tier age categorization
    if (age >= 18) {
      // Adult — full access
      sessionStorage.setItem(AGE_GATE_KEY, 'adult');
      setVerified(true);
      onVerified?.('adult');
    } else if (age >= 13) {
      // ASAA teen tier (13-17) — requires parental consent
      sessionStorage.setItem(AGE_GATE_KEY, 'teen');
      onTeenDetected?.();
      // Don't auto-verify — parent must consent first
      setError('Users aged 13-17 require parental consent. Please ask a parent or guardian to approve your account.');
    } else if (age >= minimumAge) {
      // Custom minimum (if set below 13)
      sessionStorage.setItem(AGE_GATE_KEY, 'child');
      setVerified(true);
      onVerified?.('child');
    } else {
      // Under minimum age — blocked
      setBlocked(true);
      onBlocked?.();
    }
  }, [dob, minimumAge, onVerified, onBlocked]);

  if (verified) {
    return <>{children}</>;
  }

  if (blocked) {
    return (
      <div style={{ textAlign: 'center', padding: '2rem', maxWidth: '400px', margin: '0 auto' }}>
        <h2>Access Restricted</h2>
        <p>
          Sorry, you must be at least {minimumAge} years old to access this content.
          If you believe this is an error, please contact your parent or guardian.
        </p>
      </div>
    );
  }

  return (
    <div style={{ textAlign: 'center', padding: '2rem', maxWidth: '400px', margin: '0 auto' }}>
      <h2>Age Verification Required</h2>
      <p>Please enter your date of birth to continue.</p>
      <form onSubmit={handleSubmit} style={{ marginTop: '1rem' }}>
        <label htmlFor="halo-dob" style={{ display: 'block', marginBottom: '0.5rem' }}>
          Date of Birth
        </label>
        <input
          id="halo-dob"
          type="date"
          value={dob}
          onChange={(e${changeType}) => setDob(e.target.value)}
          required
          max={new Date().toISOString().split('T')[0]}
          style={{ padding: '0.5rem', fontSize: '1rem', width: '100%', boxSizing: 'border-box' }}
        />
        {error && <p style={{ color: 'red', marginTop: '0.5rem' }}>{error}</p>}
        <button
          type="submit"
          style={{
            marginTop: '1rem',
            padding: '0.75rem 2rem',
            fontSize: '1rem',
            cursor: 'pointer',
            width: '100%',
          }}
        >
          Verify Age
        </button>
      </form>
    </div>
  );
}

export default AgeGate;
`;

  return [
    {
      relativePath: `components/AgeGate.${ext}`,
      content: component,
      description: 'COPPA-compliant age gate component with DOB verification',
    },
  ];
}

function generatePlainJS(): ScaffoldFile[] {
  const code = `/**
 * AgeGate — COPPA-compliant age verification
 *
 * Blocks access for users under 13.
 * Uses date-of-birth verification (not simple yes/no).
 * Stores verification in sessionStorage (not persistent).
 *
 * Usage:
 *   const ageGate = new AgeGate(document.getElementById('app'));
 *   ageGate.onVerified = () => { showProtectedContent(); };
 *
 * Generated by Halo (runhalo.dev) — COPPA compliance scaffold
 */

class AgeGate {
  constructor(container, options = {}) {
    this.container = container;
    this.minimumAge = options.minimumAge || 13;
    this.onVerified = options.onVerified || null;
    this.onBlocked = options.onBlocked || null;
    this.storageKey = 'halo_age_verified';

    // Check if already verified this session
    if (sessionStorage.getItem(this.storageKey) === 'true') {
      if (this.onVerified) this.onVerified();
      return;
    }

    this.render();
  }

  render() {
    const today = new Date().toISOString().split('T')[0];
    this.container.innerHTML = \`
      <div style="text-align: center; padding: 2rem; max-width: 400px; margin: 0 auto;">
        <h2>Age Verification Required</h2>
        <p>Please enter your date of birth to continue.</p>
        <form id="halo-age-form" style="margin-top: 1rem;">
          <label for="halo-dob" style="display: block; margin-bottom: 0.5rem;">Date of Birth</label>
          <input id="halo-dob" type="date" required max="\${today}"
            style="padding: 0.5rem; font-size: 1rem; width: 100%; box-sizing: border-box;" />
          <div id="halo-age-error" style="color: red; margin-top: 0.5rem; display: none;"></div>
          <button type="submit"
            style="margin-top: 1rem; padding: 0.75rem 2rem; font-size: 1rem; cursor: pointer; width: 100%;">
            Verify Age
          </button>
        </form>
      </div>
    \`;

    this.container.querySelector('#halo-age-form').addEventListener('submit', (e) => {
      e.preventDefault();
      this.verify();
    });
  }

  verify() {
    const dobInput = this.container.querySelector('#halo-dob');
    const errorDiv = this.container.querySelector('#halo-age-error');

    if (!dobInput.value) {
      errorDiv.textContent = 'Please enter your date of birth.';
      errorDiv.style.display = 'block';
      return;
    }

    const birthDate = new Date(dobInput.value);
    const today = new Date();
    let age = today.getFullYear() - birthDate.getFullYear();
    const monthDiff = today.getMonth() - birthDate.getMonth();
    if (monthDiff < 0 || (monthDiff === 0 && today.getDate() < birthDate.getDate())) {
      age--;
    }

    if (age >= this.minimumAge) {
      sessionStorage.setItem(this.storageKey, 'true');
      if (this.onVerified) this.onVerified();
    } else {
      this.container.innerHTML = \`
        <div style="text-align: center; padding: 2rem; max-width: 400px; margin: 0 auto;">
          <h2>Access Restricted</h2>
          <p>Sorry, you must be at least \${this.minimumAge} years old to access this content.</p>
        </div>
      \`;
      if (this.onBlocked) this.onBlocked();
    }
  }
}

// CommonJS + ESM compatibility
if (typeof module !== 'undefined') module.exports = { AgeGate };
`;

  return [
    {
      relativePath: 'age-gate.js',
      content: code,
      description: 'COPPA-compliant age gate with DOB verification (vanilla JS)',
    },
  ];
}

export const ageGateAuthTemplate: ScaffoldTemplate = {
  scaffoldId: 'age-gate-auth',
  name: 'Age Gate Authentication',
  description: 'COPPA-compliant age verification gate that blocks users under 13 using date-of-birth verification',
  ruleIds: ['coppa-auth-001'],
  generate(framework, typescript) {
    switch (framework) {
      case 'react':
      case 'nextjs':
        return generateReact(typescript);
      default:
        return generatePlainJS();
    }
  },
};
