/**
 * Cookie Consent Banner Scaffold
 * Addresses: coppa-cookies-016
 * Generates a privacy-first cookie consent banner (deny by default)
 */

import type { Framework } from '../../framework-detect';
import type { ScaffoldTemplate, ScaffoldFile } from '../index';

function generateReact(typescript: boolean): ScaffoldFile[] {
  const ext = typescript ? 'tsx' : 'jsx';
  const propsType = typescript
    ? `\ninterface CookieConsentProps {\n  onAccept?: () => void;\n  onDecline?: () => void;\n  privacyPolicyUrl?: string;\n}\n`
    : '';
  const propsArg = typescript
    ? '{ onAccept, onDecline, privacyPolicyUrl = "/privacy" }: CookieConsentProps'
    : '{ onAccept, onDecline, privacyPolicyUrl = "/privacy" }';

  const component = `/**
 * CookieConsentBanner — COPPA-compliant cookie consent
 *
 * Privacy-first: all non-essential cookies are OFF by default.
 * No cookies are set until the user explicitly accepts.
 * Consent is stored in localStorage (not a cookie itself).
 *
 * COPPA requirement: Children's sites must not use tracking cookies
 * without verifiable parental consent.
 *
 * Usage:
 *   <CookieConsentBanner
 *     onAccept={() => enableAnalytics()}
 *     onDecline={() => console.log('User declined cookies')}
 *   />
 *
 * Generated by Halo (runhalo.dev) — COPPA compliance scaffold
 */

import React, { useState, useEffect } from 'react';
${propsType}
const CONSENT_KEY = 'halo_cookie_consent';

export function CookieConsentBanner(${propsArg}) {
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    // Only show if user hasn't made a choice yet
    const stored = localStorage.getItem(CONSENT_KEY);
    if (stored === null) {
      setVisible(true);
    }
  }, []);

  const handleAccept = () => {
    localStorage.setItem(CONSENT_KEY, 'accepted');
    setVisible(false);
    onAccept?.();
  };

  const handleDecline = () => {
    localStorage.setItem(CONSENT_KEY, 'declined');
    setVisible(false);
    onDecline?.();
  };

  if (!visible) return null;

  return (
    <div
      role="dialog"
      aria-label="Cookie consent"
      style={{
        position: 'fixed',
        bottom: 0,
        left: 0,
        right: 0,
        backgroundColor: '#1a1a2e',
        color: '#e0e0e0',
        padding: '1rem 1.5rem',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: '1rem',
        zIndex: 9999,
        boxShadow: '0 -2px 10px rgba(0, 0, 0, 0.3)',
      }}
    >
      <p style={{ margin: 0, flex: 1, minWidth: '200px', fontSize: '0.9rem' }}>
        We use cookies to improve your experience.{' '}
        <a href={privacyPolicyUrl} style={{ color: '#818cf8', textDecoration: 'underline' }}>
          Privacy Policy
        </a>
      </p>
      <div style={{ display: 'flex', gap: '0.5rem' }}>
        <button
          onClick={handleDecline}
          style={{
            padding: '0.5rem 1.25rem',
            border: '1px solid #555',
            backgroundColor: 'transparent',
            color: '#e0e0e0',
            cursor: 'pointer',
            borderRadius: '4px',
            fontSize: '0.85rem',
          }}
        >
          Decline
        </button>
        <button
          onClick={handleAccept}
          style={{
            padding: '0.5rem 1.25rem',
            border: 'none',
            backgroundColor: '#6366f1',
            color: '#fff',
            cursor: 'pointer',
            borderRadius: '4px',
            fontSize: '0.85rem',
          }}
        >
          Accept
        </button>
      </div>
    </div>
  );
}

/**
 * Check if cookies have been consented to.
 * Use this before initializing any analytics or tracking.
 *
 * Example:
 *   if (hasCookieConsent()) {
 *     initializeAnalytics();
 *   }
 */
export function hasCookieConsent()${typescript ? ': boolean' : ''} {
  if (typeof window === 'undefined') return false;
  return localStorage.getItem(CONSENT_KEY) === 'accepted';
}

export default CookieConsentBanner;
`;

  return [
    {
      relativePath: `components/CookieConsentBanner.${ext}`,
      content: component,
      description: 'COPPA-compliant cookie consent banner with deny-by-default behavior',
    },
  ];
}

function generatePlainJS(): ScaffoldFile[] {
  const code = `/**
 * CookieConsentBanner — COPPA-compliant cookie consent
 *
 * Privacy-first: all non-essential cookies are OFF by default.
 * No cookies are set until the user explicitly accepts.
 *
 * Usage:
 *   const banner = new CookieConsentBanner({
 *     onAccept: () => enableAnalytics(),
 *     onDecline: () => console.log('User declined'),
 *   });
 *
 * Generated by Halo (runhalo.dev) — COPPA compliance scaffold
 */

class CookieConsentBanner {
  constructor(options = {}) {
    this.onAccept = options.onAccept || null;
    this.onDecline = options.onDecline || null;
    this.privacyPolicyUrl = options.privacyPolicyUrl || '/privacy';
    this.storageKey = 'halo_cookie_consent';

    // Only show if user hasn't made a choice
    const stored = localStorage.getItem(this.storageKey);
    if (stored === null) {
      this.render();
    }
  }

  render() {
    const banner = document.createElement('div');
    banner.setAttribute('role', 'dialog');
    banner.setAttribute('aria-label', 'Cookie consent');
    banner.style.cssText = \`
      position: fixed; bottom: 0; left: 0; right: 0;
      background: #1a1a2e; color: #e0e0e0;
      padding: 1rem 1.5rem; display: flex; align-items: center;
      justify-content: space-between; flex-wrap: wrap; gap: 1rem;
      z-index: 9999; box-shadow: 0 -2px 10px rgba(0,0,0,0.3);
    \`;

    banner.innerHTML = \`
      <p style="margin:0; flex:1; min-width:200px; font-size:0.9rem;">
        We use cookies to improve your experience.
        <a href="\${this.privacyPolicyUrl}" style="color:#818cf8; text-decoration:underline;">Privacy Policy</a>
      </p>
      <div style="display:flex; gap:0.5rem;">
        <button id="halo-cookie-decline" style="padding:0.5rem 1.25rem; border:1px solid #555; background:transparent; color:#e0e0e0; cursor:pointer; border-radius:4px; font-size:0.85rem;">Decline</button>
        <button id="halo-cookie-accept" style="padding:0.5rem 1.25rem; border:none; background:#6366f1; color:#fff; cursor:pointer; border-radius:4px; font-size:0.85rem;">Accept</button>
      </div>
    \`;

    banner.querySelector('#halo-cookie-decline').addEventListener('click', () => {
      localStorage.setItem(this.storageKey, 'declined');
      banner.remove();
      if (this.onDecline) this.onDecline();
    });

    banner.querySelector('#halo-cookie-accept').addEventListener('click', () => {
      localStorage.setItem(this.storageKey, 'accepted');
      banner.remove();
      if (this.onAccept) this.onAccept();
    });

    document.body.appendChild(banner);
    this.element = banner;
  }
}

/**
 * Check if cookies have been consented to.
 * Use before initializing analytics or tracking.
 */
function hasCookieConsent() {
  return localStorage.getItem('halo_cookie_consent') === 'accepted';
}

if (typeof module !== 'undefined') module.exports = { CookieConsentBanner, hasCookieConsent };
`;

  return [
    {
      relativePath: 'cookie-consent.js',
      content: code,
      description: 'COPPA-compliant cookie consent banner (vanilla JS)',
    },
  ];
}

export const consentCookiesTemplate: ScaffoldTemplate = {
  scaffoldId: 'consent-cookies',
  name: 'Cookie Consent Banner',
  description: 'Privacy-first cookie consent banner with deny-by-default behavior',
  ruleIds: ['coppa-cookies-016'],
  generate(framework, typescript) {
    switch (framework) {
      case 'react':
      case 'nextjs':
        return generateReact(typescript);
      default:
        return generatePlainJS();
    }
  },
};
