/**
 * PII Sanitizer Scaffold
 * Addresses: coppa-data-002 (HIGH)
 * Generates middleware/utility to strip PII from URL parameters
 */

import type { Framework } from '../../framework-detect';
import type { ScaffoldTemplate, ScaffoldFile } from '../index';

function generateReact(typescript: boolean): ScaffoldFile[] {
  const ext = typescript ? 'ts' : 'js';
  const typeAnnotations = typescript;

  // Utility file (framework-agnostic, used by both React and Next.js)
  const utility = `/**
 * PII Sanitizer — strips personally identifiable information from URLs
 *
 * COPPA requires that children's personal information is not transmitted
 * in URL parameters, query strings, or referrer headers. This utility
 * detects and removes PII patterns from URLs before they are used.
 *
 * Common PII fields detected: email, name, phone, dob, ssn, address,
 * birthday, age, school, parent, guardian.
 *
 * Usage:
 *   import { sanitizeUrl, containsPII } from './pii-sanitizer';
 *
 *   const cleanUrl = sanitizeUrl('https://api.example.com/users?email=child@test.com&name=TestUser');
 *   // => 'https://api.example.com/users'
 *
 *   if (containsPII(url)) {
 *     console.warn('URL contains PII — sanitizing before request');
 *   }
 *
 * Generated by Halo (runhalo.dev) — COPPA compliance scaffold
 */

/** PII parameter patterns — case-insensitive matching */
const PII_PATTERNS${typeAnnotations ? ': readonly string[]' : ''} = [
  'email', 'e-mail', 'mail',
  'name', 'first_name', 'last_name', 'firstname', 'lastname', 'full_name', 'fullname',
  'username', 'user_name', 'display_name',
  'phone', 'telephone', 'tel', 'mobile', 'cell',
  'dob', 'date_of_birth', 'dateofbirth', 'birthday', 'birth_date', 'birthdate',
  'age',
  'ssn', 'social_security', 'national_id',
  'address', 'street', 'city', 'zip', 'zipcode', 'zip_code', 'postal',
  'school', 'school_name',
  'parent', 'guardian', 'parent_email', 'guardian_email',
  'child', 'child_name', 'kid',
  'password', 'passwd', 'pwd',
  'token', 'api_key', 'apikey', 'secret',
]${typeAnnotations ? ' as const' : ''};

/**
 * Check if a URL contains PII in its query parameters
 */
export function containsPII(url${typeAnnotations ? ': string' : ''})${typeAnnotations ? ': boolean' : ''} {
  try {
    const parsed = new URL(url, 'https://placeholder.local');
    const params = Array.from(parsed.searchParams.keys());
    return params.some(param =>
      PII_PATTERNS.some(pattern =>
        param.toLowerCase().includes(pattern.toLowerCase())
      )
    );
  } catch {
    return false;
  }
}

/**
 * Remove PII parameters from a URL, preserving non-PII params
 */
export function sanitizeUrl(url${typeAnnotations ? ': string' : ''})${typeAnnotations ? ': string' : ''} {
  try {
    const parsed = new URL(url, 'https://placeholder.local');
    const toRemove${typeAnnotations ? ': string[]' : ''} = [];

    parsed.searchParams.forEach((_, key) => {
      if (PII_PATTERNS.some(pattern => key.toLowerCase().includes(pattern.toLowerCase()))) {
        toRemove.push(key);
      }
    });

    toRemove.forEach(key => parsed.searchParams.delete(key));

    // If original was relative, return relative
    if (!url.startsWith('http')) {
      return parsed.pathname + parsed.search + parsed.hash;
    }

    return parsed.toString();
  } catch {
    return url;
  }
}

/**
 * Extract PII fields from a URL (for logging/auditing)
 * Returns the parameter names (NOT values) that match PII patterns
 */
export function detectPIIFields(url${typeAnnotations ? ': string' : ''})${typeAnnotations ? ': string[]' : ''} {
  try {
    const parsed = new URL(url, 'https://placeholder.local');
    return Array.from(parsed.searchParams.keys()).filter(key =>
      PII_PATTERNS.some(pattern => key.toLowerCase().includes(pattern.toLowerCase()))
    );
  } catch {
    return [];
  }
}

/**
 * Middleware-style sanitizer for fetch/axios interceptors
 *
 * Usage with fetch:
 *   const originalFetch = window.fetch;
 *   window.fetch = (url, options) => {
 *     return originalFetch(sanitizeFetchUrl(url), options);
 *   };
 */
export function sanitizeFetchUrl(input${typeAnnotations ? ': string | URL | Request' : ''})${typeAnnotations ? ': string | URL | Request' : ''} {
  if (typeof input === 'string') {
    return sanitizeUrl(input);
  }
  if (input instanceof URL) {
    return new URL(sanitizeUrl(input.toString()));
  }
  // Request object — sanitize the URL
  if (input instanceof Request) {
    const cleanUrl = sanitizeUrl(input.url);
    return new Request(cleanUrl, input);
  }
  return input;
}

export { PII_PATTERNS };
`;

  return [
    {
      relativePath: `utils/pii-sanitizer.${ext}`,
      content: utility,
      description: 'PII detection and URL sanitization utility for COPPA compliance',
    },
  ];
}

function generatePlainJS(): ScaffoldFile[] {
  const code = `/**
 * PII Sanitizer — strips personally identifiable information from URLs
 *
 * COPPA requires that children's personal information is not transmitted
 * in URL parameters, query strings, or referrer headers.
 *
 * Usage:
 *   const { sanitizeUrl, containsPII } = require('./pii-sanitizer');
 *   const cleanUrl = sanitizeUrl('https://api.example.com/users?email=child@test.com');
 *
 * Express middleware:
 *   app.use(piiMiddleware());
 *
 * Generated by Halo (runhalo.dev) — COPPA compliance scaffold
 */

const PII_PATTERNS = [
  'email', 'e-mail', 'mail',
  'name', 'first_name', 'last_name', 'firstname', 'lastname', 'full_name', 'fullname',
  'username', 'user_name', 'display_name',
  'phone', 'telephone', 'tel', 'mobile', 'cell',
  'dob', 'date_of_birth', 'dateofbirth', 'birthday', 'birth_date', 'birthdate',
  'age',
  'ssn', 'social_security', 'national_id',
  'address', 'street', 'city', 'zip', 'zipcode', 'zip_code', 'postal',
  'school', 'school_name',
  'parent', 'guardian', 'parent_email', 'guardian_email',
  'child', 'child_name', 'kid',
  'password', 'passwd', 'pwd',
  'token', 'api_key', 'apikey', 'secret',
];

function containsPII(url) {
  try {
    const parsed = new URL(url, 'https://placeholder.local');
    const params = Array.from(parsed.searchParams.keys());
    return params.some(param =>
      PII_PATTERNS.some(pattern =>
        param.toLowerCase().includes(pattern.toLowerCase())
      )
    );
  } catch {
    return false;
  }
}

function sanitizeUrl(url) {
  try {
    const parsed = new URL(url, 'https://placeholder.local');
    const toRemove = [];

    parsed.searchParams.forEach((_, key) => {
      if (PII_PATTERNS.some(pattern => key.toLowerCase().includes(pattern.toLowerCase()))) {
        toRemove.push(key);
      }
    });

    toRemove.forEach(key => parsed.searchParams.delete(key));

    if (!url.startsWith('http')) {
      return parsed.pathname + parsed.search + parsed.hash;
    }

    return parsed.toString();
  } catch {
    return url;
  }
}

/**
 * Express middleware — strips PII from query parameters
 *
 * Usage:
 *   const { piiMiddleware } = require('./pii-sanitizer');
 *   app.use(piiMiddleware());
 */
function piiMiddleware() {
  return function (req, res, next) {
    const piiKeys = Object.keys(req.query).filter(key =>
      PII_PATTERNS.some(pattern => key.toLowerCase().includes(pattern.toLowerCase()))
    );

    if (piiKeys.length > 0) {
      console.warn('[Halo PII Guard] Stripped PII params from request:', piiKeys.join(', '));
      piiKeys.forEach(key => delete req.query[key]);
    }

    next();
  };
}

module.exports = { containsPII, sanitizeUrl, piiMiddleware, PII_PATTERNS };
`;

  return [
    {
      relativePath: 'pii-sanitizer.js',
      content: code,
      description: 'PII sanitizer with Express middleware (vanilla JS/Node.js)',
    },
  ];
}

export const piiSanitizerTemplate: ScaffoldTemplate = {
  scaffoldId: 'pii-sanitizer',
  name: 'PII Sanitizer',
  description: 'Strips personally identifiable information from URL parameters to prevent COPPA violations',
  ruleIds: ['coppa-data-002'],
  generate(framework, typescript) {
    switch (framework) {
      case 'react':
      case 'nextjs':
        return generateReact(typescript);
      default:
        return generatePlainJS();
    }
  },
};
